name: 'Terraform Destroy'

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions UI

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment:
      name: production  # Use an environment with protection rules if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        run: terraform init
        env:
          TF_LOG: ERROR

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_LOG: ERROR
          TERRAFORM_CLOUD_TOKEN: ${{ secrets.TF_API_TOKEN }}
